### ISSUE TITLE
Request: Ability to remove a task

### ISSUE THREAD

**Issue by MasterOfHash** [Explv/Explvs-AIO#10]
Note: These are all fixes I have in the works. I'll be opening PRs this weekend with the fixes.

**Comment by Explv** [comment]
Just a note, this is already a feature (although not an obvious one) you can right click on a task to delete. Not sure if there are any bugs with that functionality

**Comment by MasterOfHash** [comment]
Yep I just saw that in the code.. But I don't know if it will actually work when you load a configuration from JSON after looking at the code.

I think this is fine though. Thanks!
