### ISSUE TITLE
Quest config updates before quest is fully done, when quest ends with cut scene

### ISSUE THREAD

**Issue by RealPoke** [Explv/Explvs-AIO#26]
This actually seems to not matter at all, it still tries to do things in the cut scene, like spam walking or attempt to logout and get stuck.

Seems like the `completedConfigVal` is making it continue before the actual quest is done since the last config value is 5 but it changes to 5 even before the quest is fully complete.

_Originally posted by @RealPoke in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTQ5ODU0OTA0OnYy/pull_request_review_threads/discussion_

**Comment by RealPoke** [comment]
This is not a big problem, but might be a good thing to make the auto quest completion check based on config disable able in the individual quests, and have the individual quest able to have custom checks.

**Comment by RealPoke** [comment]
Could also make the value `completedConfigVal` optional?

**Comment by Explv** [comment]
There is a `canExit` function in activities that you can override. If the function returns true, the activity will keep executing even if `Task.isComplete` returns true.

In this case you should override the `canExit` function to return false if the player is in the cut scene.

**Comment by RealPoke** [comment]
Ok, great that will work!
