### ISSUE TITLE
Loop task can be set to a timestamp

### ISSUE THREAD

**Issue by RealPoke** [Explv/Explvs-AIO#28]
It would be great if the loop task had an option to set a timestamp, so that it would keep looping until that specific time.
Could either be with a specific date or just a time of the day.

**Comment by RealPoke** [comment]
@MasterOfHash do you think this would be possible to be implemented?

**Comment by Explv** [comment]
This shouldn't be hard, we'll need to make sure the GUI changes are backwards compatible in terms of JSON serializing / deserializing to ensure it doesn't break people's existing saved configs

**Comment by MasterOfHash** [comment]
Yeah that's true. Would you want to do a full loop or check the time at each step in the loop and short circuit the loop @RealPoke ?

**Comment by RealPoke** [comment]
I think it would be best to have it stop as soon as it hits the timestamp, so to short sircuit the loop would be great if possible :D

**Comment by MasterOfHash** [comment]
Oh okay, I was thinking the "Stop at end of loop" approach. I'm good with either one, though. We could also have a "Timestamp" input and an "Interrept Loop" checkbox button?

**Comment by Explv** [comment]
I think timestamp and an interrupt option makes the most sense here.

**Comment by MasterOfHash** [comment]
That’s good with me.
