### ISSUE TITLE
Trade task

### ISSUE THREAD

**Issue by RealPoke** [Explv/Explvs-AIO#29]
Having the ability to add a task where the bot goes to a location with specific item(s) and either waits for a specific person to trade it or goes and sends a trade request itself.

**Comment by MasterOfHash** [comment]
Sorry, this is part of automuling. I've implemented these scripts already but they're not allowed to be freely distributed.

**Comment by RealPoke** [comment]
Oh, didn't think of that. Was more to have multiple bots, like one mining and giving ores to a smith. So we are not allowed to have this?

**Comment by MasterOfHash** [comment]
I would opt that this is pretty close to automuling and is not a great script to add.

@RealPoke you seem to have the chops to implement it yourself? If you want, I've implemented a ton of scripts under a `PlayerInteraction` task panel which include walkers, traders, etc.

I could help you out in making this if you'd like!

**Comment by Explv** [comment]
@MasterOfHash if you're referring to SDN script rules, I have no problem diverging this repo from the SDN version. I can just exclude the changes from the SDN script. I may decommission the SDN script at some point anyway, seeing as it is more of a hindrance in terms of features, and less user friendly than just downloading from here.

**Comment by MasterOfHash** [comment]
I was but I’m also personally not comfortable contributing mulling scripts. Don’t want to make it too easy it it’s going to crash the demand for GP.

**Comment by RealPoke** [comment]
> @MasterOfHash if you're referring to SDN script rules, I have no problem diverging this repo from the SDN version. I can just exclude the changes from the SDN script. I may decommission the SDN script at some point anyway, seeing as it is more of a hindrance in terms of features, and less user friendly than just downloading from here.

If this is the case then we should make this the AIO to rule them all haha.
@MasterOfHash I can look into adding this, but I most likely need a bit of help :)

**Comment by MasterOfHash** [comment]
I’m happy to help! Shoot me a message on the forum if you’d like. 

But I would still opt that we don’t contribute mulling (trading) scripts directly to this OSS project. I’m gold farming and want to keep the demand and price high as long as possible. Haha

**Comment by RealPoke** [comment]
Well, it mostly comes down to not adding the best money making methods then :P

**Comment by MasterOfHash** [comment]
Haha that’s true. But mulling scripts are more valuable than money making
scripts since you can scale a small operation.

I’d be happy to send you my trading scripts when I’m at my computer next if
you want. I just don’t want to contribute them here.

**Comment by MasterOfHash** [comment]
@Explv @RealPoke thoughts about closing this issue? I'd happily privately share my trade scripts on request but would strongly vote against committing anything of the sort to this project.

**Comment by RealPoke** [comment]
I don't see the big problem, I don't think people are going to use it for muling.
But if you think so then yes, we can always take it up later again.

**Comment by MasterOfHash** [comment]
What if we bake that functionality into utility functions and the actual
skilling scripts? Like I said I’m down to contribute and share but I make
money farming so I don’t want it to be too easy for others to just do it
out of the box.

**Comment by RealPoke** [comment]
I see where you are coming from, so let's not do this for a now. Might bring it up later.
