### ISSUE TITLE
Cloud based analytics and storage

### ISSUE THREAD

**Issue by MasterOfHash** [Explv/Explvs-AIO#31]
- It would be nice to be able to read/save configs from the cloud (on a per-user basis, backed by AWS)
- It would be nice to be able to have helpers to persist analytics and events to the cloud

I have these both implemented but am not sure how widely they should be shared or if they're worth PRing. Without setting up your own DynamoDB instance you'd have to share my table for cloud config saves.

I also have a lot of bot analytics built into API Gateway -> Lambda -> Dynamo but unless I want to segment them by user and offer free cloud storage to folks, I'd have to offer the ability to config to your own instance.

@Explv what do you think? Do you want these added? I could make them generic but users would have to implement their own instances to consume them.

**Comment by Explv** [comment]
It sounds cool but I'm not sure how many people would use it, considering it would require setup and configuration on their end.

**Comment by MasterOfHash** [comment]
Yeah I can just keep them on my branch. It’s nice for me because I can
share configurations and logging across dedicated servers that I setup on
my laptop.

**Comment by MasterOfHash** [comment]
Yeah I can just keep them on my branch. It’s nice for me because I can share configurations and logging across dedicated servers that I setup on my laptop.
