### ISSUE TITLE
Script does not start when run for second time

### ISSUE THREAD

**Issue by Explv** [Explv/Explvs-AIO#32]
How to reproduce:

1. Start the script
2. Stop the script
3. Start the script (without refreshing in script list) - script will crash

Bug:

It seems that for some reason when the script is run for the second time, without a refresh, image loading using `Class.getResourceAsStream()` returns null (No idea why)

**Comment by RealPoke** [comment]
Could this be related to the permissions problem we are also experiencing?

**Comment by Explv** [comment]
@RealPoke this is unrelated
