### ISSUE TITLE
Setting this up on Intellij

### ISSUE THREAD

**Issue by battlerme** [Explv/Explvs-AIO#47]
How do I set this up on intellij? I imported it into intellij, added osbot as a global library, marked the resource folder as the resource root and then built the artifact with the module output. But I get the following error when I run it on osbot: 
![capture](https://user-images.githubusercontent.com/46695456/51149523-5754cb00-1817-11e9-8373-65d82ca2e784.PNG)
I don't have this issue when I use the jars releases, so I am not sure what I am doing wrong? Thanks!

**Comment by MasterOfHash** [comment]
You’re not exporting your resources into the jar. You want to make sure
you’re copying the resources directory into the jar root.

**Comment by battlerme** [comment]
![help1](https://user-images.githubusercontent.com/46695456/51154187-d520d280-1827-11e9-9d22-546136b37eb2.PNG)
![help2](https://user-images.githubusercontent.com/46695456/51154192-d8b45980-1827-11e9-9424-74c3a8e2fc84.PNG)
I think I have done it this way now, but still get a similar error message!

**Comment by MasterOfHash** [comment]
Hmm the issue you're hitting is definitely a resource one.. I moved my
resources because they're not setup to spec in this repo. Mine are nested
within /src/ and copied over like that. You might need to nest your
resources within root/AIO

**Comment by RealPoke** [comment]
Ahh, this is what I needed too :D

**Comment by battlerme** [comment]
Thank you!:)

**Comment by RealPoke** [comment]
I think this information should be somewhere more accessible, like the readme would be awesome!

**Comment by Explv** [comment]
@RealPoke https://github.com/Explv/Explvs-AIO/wiki/Local-Development-Setup
