### ISSUE TITLE
Tutorial Island, failed to open settings

### ISSUE THREAD

**Issue by Azn2000** [Explv/Explvs-AIO#52]
Because of the change in the Event EnabledFixedModeEvent to Line 26
`} else if (Tab.SETTINGS.isDisabled(getBot())) {`
It can not execute probably in the Tutorial Settings section, because the Game says its disabled.
But it isn't, did a really messy workaround to fix it for me at least.
`} else if (Tab.SETTINGS.isDisabled(getBot()) && getConfigs().get(281) == 1000) {`

Better solution needs to be found.

**Comment by Explv** [comment]
This should be working now. Re-open if not
