### ISSUE TITLE
Doesn't do ConfigEvents when started on TutorialIsland

### ISSUE THREAD

**Issue by Azn2000** [Explv/Explvs-AIO#58]
If you start your bot on Tutorial Island it will not do the SetupEvents even when it has left the Tutorial Island, could get you stuck in quests and stuff

**Comment by Azn2000** [comment]
I found out why -> on Tutorial Island roofs are disabled by default, but when you leave tutorial island it will switch back to roofs shown, so the configs need to be set after tutorial island, but beware of the noob guide, if you try to change your settings while he tries to talk to you you get stuck

**Comment by Explv** [comment]
Working on a fix now
