### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by MasterOfHash** [Explv/Explvs-AIO#59]
What is your basis for versioning? We should try and respect [Semantic Versioning](https://semver.org/)

**Comment by Explv** [comment]
@MasterOfHash I would use semantic versioning, but the `ScriptManifest` stores the version as a double and not a String, so you can't use `major.minor.patch`. As I need the version to be incremented every update to work with the `VersionChecker`, I am incrementing by `0.1`.

**Comment by Explv** [comment]
We can probably use semantic versioning if we just have a Version file with a static String variable in there indicating the current version.

**Comment by paulgerlich-wf** [comment]
Not much use really, but as a consumer and contributor it makes it easier for me to know if I want to pull in the next release or current master. Right know the major/minor version is arbitrary which makes it a bit confusing as to whether or not I should anticipate merge conflicts or API changes

**Comment by paulgerlich-wf** [comment]
If we could just make the major versions more meaningful (it's OK to release software that's like V 1.241) then that might help establish more clarity? What are your thoughts?

**Comment by Explv** [comment]
@paulgerlich-wf We can just use semantic versioning. I'll add a String constant to the main script class, and we can use that instead of the `ScriptManifest` version
