### ISSUE TITLE
Break Manager does not log user out

### ISSUE THREAD

**Issue by MasterOfHash** [Explv/Explvs-AIO#64]

**Comment by Explv** [comment]
Pretty sure overriding the break manager is broken at the moment, not just an issue with this script, waiting for a fix from OSBot devs.

**Comment by MasterOfHash** [comment]
That make sense. I ended up using a work around with a login script that
you wrote to fix my use case.

**Comment by Explv** [comment]
Apparently Patrick has fixed this, so I expect it will be working either in the dev build, or in the next OSBot release

**Comment by Explv** [comment]
@RealPoke that issue should now be fixed
