### ISSUE TITLE
Grand Exchange Tasks should have the option to be idempotent

### ISSUE THREAD

**Issue by pgerlich** [Explv/Explvs-AIO#70]
Due to low CPU mode and script break inconsistencies, a GE buy task can end up occurring twice. It would be nice to have a check box to ensure idempotency (make sure this buy task only occurs once / if we don't already have that item/quantity in our inventory or bank)

I have this added locally and am happy to contribute it, if it is something we want. The default value will be False.

@RealPoke @Explv @Azn2000

**Comment by RealPoke** [comment]
Do a pull request, that's the best way to get your code reviewed and accepted :)
I would love this.

**Comment by RealPoke** [comment]
Is these accounts both of you?

**Comment by Explv** [comment]
Why does the task happen twice?

**Comment by pgerlich** [comment]
Oops. Yeah I was using an account for the sake of making private SDN
scripts but they get mixed up. :)

**Comment by pgerlich** [comment]
A variety of reasons. It could be due to script ordering issues, a break
happening in the middle of a loop, etc.
