### ISSUE TITLE
Save/Load buttons don't do anything?

### ISSUE THREAD

**Issue by MasterOfHash** [Explv/Explvs-AIO#9]
Not sure about this one. I haven't started looking into it, but it doesn't seem to work for me once I actually create a JAR and load it into the client.

Running the GUI code locally seems to work. Is there a permissions issue? Any help here would be appreciated.

**Comment by Explv** [comment]
Saving / Loading should work, I'll verify when I have time

**Comment by MasterOfHash** [comment]
Okay no worries. It might be something with the way I loaded up the project. For some reason, my resources weren't being recognized unless I moved them inside the src directory..

**Comment by Explv** [comment]
@MasterOfHash you need to create a "resources" directory in the root of the .jar, and then configure it such that the resources are copied to that directory

**Comment by MasterOfHash** [comment]
Ah makes sense. I can get that setup. Let me know what you see regarding the Save/load. If I could get that working locally it would definitely improve my dev cycle time by a good margin

**Comment by MasterOfHash** [comment]
I'll figure this out myself.. I don't think it's an issue everywhere.
